### ISSUE TITLE
socket.error: [Errno 92] Protocol not available

### ISSUE THREAD

**Issue by voidpp** [balloob/pychromecast#55] opened 2015-08-15 17:08 UTC
My code:
```py
import pychromecast
pychromecast.get_chromecasts_as_dict().keys()
```
The first result:
```
Traceback (most recent call last):
  File "cc.py", line 3, in <module>
    print pychromecast.get_chromecasts_as_dict().keys()
  File "/usr/local/lib/python2.7/dist-packages/pychromecast/__init__.py", line 98, in get_chromecasts_as_dict
    for cc in get_chromecasts(tries=tries, **filters)}
  File "/usr/local/lib/python2.7/dist-packages/pychromecast/__init__.py", line 60, in get_chromecasts
    cc_list = set(_get_all_chromecasts(tries=tries))
  File "/usr/local/lib/python2.7/dist-packages/pychromecast/__init__.py", line 26, in _get_all_chromecasts
    hosts = discover_chromecasts()
  File "/usr/local/lib/python2.7/dist-packages/pychromecast/discovery.py", line 67, in discover_chromecasts
    browser.cancel()
UnboundLocalError: local variable 'browser' referenced before assignment
```
The original `PyChromecast` code:
```py
def discover_chromecasts(max_devices=None, timeout=DISCOVER_TIMEOUT):
    """ Discover chromecasts on the network. """
    try:
        zconf = Zeroconf()
        listener = CastListener()
        browser = ServiceBrowser(zconf, "_googlecast._tcp.local.", listener)

        if max_devices is None:
            time.sleep(timeout)
            return listener.devices

        else:
            start = time.time()

            while (time.time() - start < timeout and
                   listener.count < max_devices):
                time.sleep(.1)

            return listener.devices
    finally:
        browser.cancel()
        zconf.close()
```
After some fixup:
```py
def discover_chromecasts(max_devices=None, timeout=DISCOVER_TIMEOUT):
    """ Discover chromecasts on the network. """
    browser = None
    zconf = None
    try:
        zconf = Zeroconf()
        listener = CastListener()
        browser = ServiceBrowser(zconf, "_googlecast._tcp.local.", listener)

        if max_devices is None:
            time.sleep(timeout)
            return listener.devices

        else:
            start = time.time()

            while (time.time() - start < timeout and
                   listener.count < max_devices):
                time.sleep(.1)

            return listener.devices
    finally:
        if browser:
            browser.cancel()
        if zconf:
            zconf.close()
```
Detailed error:
```
Traceback (most recent call last):
  File "cc.py", line 3, in <module>
    print pychromecast.get_chromecasts_as_dict().keys()
  File "/usr/local/lib/python2.7/dist-packages/pychromecast/__init__.py", line 98, in get_chromecasts_as_dict
    for cc in get_chromecasts(tries=tries, **filters)}
  File "/usr/local/lib/python2.7/dist-packages/pychromecast/__init__.py", line 60, in get_chromecasts
    cc_list = set(_get_all_chromecasts(tries=tries))
  File "/usr/local/lib/python2.7/dist-packages/pychromecast/__init__.py", line 26, in _get_all_chromecasts
    hosts = discover_chromecasts()
  File "/usr/local/lib/python2.7/dist-packages/pychromecast/discovery.py", line 49, in discover_chromecasts
    zconf = Zeroconf()
  File "/usr/local/lib/python2.7/dist-packages/zeroconf.py", line 1336, in __init__
    self._listen_socket = new_socket()
  File "/usr/local/lib/python2.7/dist-packages/zeroconf.py", line 1303, in new_socket
    s.setsockopt(socket.SOL_SOCKET, reuseport, 1)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 92] Protocol not available
```
versions:
```
PyChromecast==0.6.9
protobuf==3.0.0a3
zeroconf==0.17.2
requests==2.7.0
```
system:
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:        14.04
Codename:       trusty
```

Any fixing ideas?

**Comment by balloob** [comment] 2015-08-18 05:49
I have not heard of anyone with these problems before.

It seems to be a bug in the [zeroconf dependency](https://github.com/jstasiak/python-zeroconf).

As a workaround, you can avoid using the zeroconf dependency. Assuming you know the IP address of your Cast device:
```python
import pychromecast
cast = pychromecast.Chromecast('192.168.1.9')
```

**Comment by voidpp** [comment] 2015-08-18 17:23
Thx for the help, it works in this way.
The hardware is an Odroid U3, but i think it should not be important...

**Comment by balloob** [comment] 2015-08-18 20:01
Excellent!

I'll be closing this as it is not a bug with PyChromecast.

**Closed by balloob** 2015-08-18 20:01 UTC
