### ISSUE TITLE
Is there a way to turn off the tv with py?

### ISSUE THREAD

**Issue by johansson505** [balloob/pychromecast#210] opened 2018-01-18 20:47 UTC
So is there a way? Cuz now it seems like the only thing I can do is to reboot the chromecast but I would like to turn of the tv.
I know that Google Home does it in a way, but don't know how.

**Comment by OttoWinter** [comment] 2018-01-18 20:55
Duplicate of #196 - and the conclusion there was that it's not (currently) possible.

**Closed** 2018-01-18 21:05 UTC
