### ISSUE TITLE
Thread sometimes bails with'Bad file descriptor'

### ISSUE THREAD

**Issue by paultag** [balloob/pychromecast#59] opened 2015-09-21 04:25 UTC
```
[paultag@cassiel:~][⌚ 12:24 AM] ♥  python
Python 3.4.3+ (default, Jul 28 2015, 13:17:50) 
[GCC 4.9.3] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pychromecast
>>> pychromecast.get_chromecasts_as_dict()
{}
>>> Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/home/paultag/.virtualenvs/cuttlebot/lib/python3.4/site-packages/zeroconf.py", line 1063, in run
    handler(self.zc)
  File "/home/paultag/.virtualenvs/cuttlebot/lib/python3.4/site-packages/zeroconf.py", line 1014, in <lambda>
    state_change=state_change,
  File "/home/paultag/.virtualenvs/cuttlebot/lib/python3.4/site-packages/zeroconf.py", line 931, in fire
    h(**kwargs)
  File "/home/paultag/.virtualenvs/cuttlebot/lib/python3.4/site-packages/zeroconf.py", line 989, in on_change
    listener.add_service(*args)
  File "/home/paultag/.virtualenvs/cuttlebot/lib/python3.4/site-packages/pychromecast/discovery.py", line 34, in add_service
    service = zconf.get_service_info(typ, name)
  File "/home/paultag/.virtualenvs/cuttlebot/lib/python3.4/site-packages/zeroconf.py", line 1398, in get_service_info
    if info.request(self, timeout):
  File "/home/paultag/.virtualenvs/cuttlebot/lib/python3.4/site-packages/zeroconf.py", line 1221, in request
    zc.send(out)
  File "/home/paultag/.virtualenvs/cuttlebot/lib/python3.4/site-packages/zeroconf.py", line 1657, in send
    bytes_sent = s.sendto(packet, 0, (addr, port))
OSError: [Errno 9] Bad file descriptor
```

**Comment by rmkraus** [comment] 2015-09-21 05:05
That's in the zeroconf library and outside of the control of this library. It shouldn't be causing any issues though. It should only throw that exception during discovery.

**Comment by AnsgarSchmidt** [comment] 2016-10-14 07:05
Can you catch it within the library and just ignore it?

**Comment by hugovk** [comment] 2016-11-25 22:39
This is a duplicate of https://github.com/balloob/pychromecast/issues/120 and will be fixed by https://github.com/jstasiak/python-zeroconf/pull/88.

**Comment by thachnb85** [comment] 2017-01-01 03:16
Hi @hugovk  Is there anyway to get it fixed manually in python-zeroconf?
Thanks

**Comment by 1337sup3rh4x0r** [comment] 2017-01-16 10:00
Manually applying the changes from https://github.com/jstasiak/python-zeroconf/pull/88/commits/4475cbc723ec146bb5afb1d4931f8fb1c503b398 solves this issue for me

**Comment by jstasiak** [comment] 2017-02-03 14:22
FYI python-zeroconf 0.18.0 with the relevant patch has just been released.

**Comment by balloob** [comment] 2017-02-03 17:06
Thanks @jstasiak !

**Closed** 2017-02-03 17:06 UTC
